---
title: Tips for Clinical Rotations
author: Daniel Pique
date: '2018-09-27'
slug: tips-for-clinical-rotations
categories:
  - medical school
tags:
  - advice
---

Below are some tips that I learned for med school from my first rotation:

1. Always carry extra food (eg granola bars) in your pockets. This can be for you or for a resident that you work with. Always bring gum or something to freshen your breath after you eat as you will be talking to patients and team members up close.

2. Ask for *specific* feedback from your residents and attendings. Ask `How is my one liner for my presentation?` rather than `Do you have any feedback for me?`

3. Show that you are interested by asking questions and volunteering to do minor tasks, if the opportunity arises.

4. Listen or participate as part of the bedside physical exam, especially if there is an interesting physical finding. May or may not need to preface with "Can I listen?"

5. Be nice and friendly toward the nurses, hospital staff, other medical students on the rotations, and to your residents. While you may not speak much directly to your attending, they (along with the others on the team who will be evaluating you) will take note of your general demeanor.

6. Show that you are interested in your patients by reading on their diseases (as well as the diseases of the other patients on the team.)

7. Practice your presentation, especially your one-liner, assessment (+ summary statement), and plan. It may seem like the residents have this down solidly, but I have noticed that the residents with the best presentations write down their assessment and plan (probably the most important part of the SOAP note).

8. Let your resident or attending know in advance if you have lectures, class, or need to be somewhere. Have their phone number in case you are running late.

9. 