---
title: Tips for transitioning between PhD and 3rd year
author: Daniel Pique
date: '2018-11-10'
slug: tips-for-transitioning-between-phd-and-3rd-year
categories:
  - medical school
  - graduate school
tags:
  - advice
  - Einstein
---

This post is about transitioning between graduate school and medical school in the MD-PhD program. The transition should begin early in your graduate school career. Try shadowing or taking part in a clinic, perhaps once per week, to both develop your clinical skills and also identify clinical specialties that you want to go in to. Some programs have this built in, others you may have to seek this out or set it up. 

As a 3rd year medical student, you will have 4 major tasks: Taking a history, performing a physical exam, presenting patients to an attending, and writing a note on the patient. In brief, listening, examining, speaking, and writing. 

1. Taking a history: SMASHED FM. 

1. Presenting patients: Keep it short, fluid, and succinct. The attending will fill in or ask about any major gaps - it's okay for this to happen. Better to have a short, incomplete 1 min presentation than a long 10 minute presentation.

1. Ask the person you are shadowing if you can do the history or physical alone or with them watching.

1. Practice your clinical presentations to attendings (especially at the beginning) and note writing skills. When interviewing patients, try to simulate the USMLE Step 2 CK, where you have 15 minutes for the patient encounter and 10 minutes for writing a note.


