---
title: Starting a Project with the End in Mind
author: Daniel Piqué
date: '2020-02-16'
slug: how-to-start-a-project
categories:
  - graduate school
  - business
  - Resources
tags: []
---


I recently spoke with George Church as part of an interview. He said that he's started 24 companies in the last 24 months. How, I wondered? He starts every project with a company (for or non-profit) in mind.

But how do you know how the project will end? What will it look like at the end?
Oftentimes, this can be difficult. 


One way is to have a framework structure for all of the possible endpoints for a project. I believe that there are a handful of definable endpoints that are most common in life and statistical sciences. Keeping in mind which one you want is helpful during the development cycle. And keep in mind that this can change as the project evolves.

I was taught that the main aim of academic scientific research is to write and publish manuscripts. Review articles, methods, and software are okay, but are 2nd tier to manuscripts that describe original research. But I believe this is changing. 


Research

Innovation in work



Here they are:

* Published manuscript (literature review, methods, or discovery)

* Preprint

* Conference presentation (oral or poster)

* Book or book chapter

* Software (open vs closed source, open access, free or paid). Who is the audience (other programmers or non-technical users?)

* Web or mobile application

* Video

* Blog post

* Physical product

* Company (for or non-profit)

Even just knowing that these forms of communication and delivery exist

That's all for now. Let me know if you have additional thoughts.

Daniel
